### ISSUE TITLE
Feature request: Add support for server_knowledge parameter (delta requests)

### ISSUE THREAD

**Issue by rgamage** [jsmarble/YNAB.Rest#14]
It would be nice to add support for delta requests, where the client can pass the last_knowledge_of_server parameter to the endpoint, which will fetch only data that has changed since the last fetch corresponding to that parameter.  This is supported in the YNAB API itself (on certain endpoints) and would only require adding the parameter to the IApiClient definition, and perhaps adding the property to some of the data models.

Documentation is here:
https://api.ynab.com/#deltas

**Comment by jsmarble** [comment]
Thanks for writing a good request and linking to the docs. That was helpful to get me moving on this. In the end, I cleaned up some previous implementations for a couple of APIs and added support to those existing ones for making requests with `last_knowledge_of_server`. Cheers!

**Comment by rgamage** [comment]
Excellent, thanks for the quick response!
