### ISSUE TITLE
New AccountType enumerations needed

### ISSUE THREAD

**Issue by websmartcentral** [jsmarble/YNAB.Rest#7]
Hi 

I've noticed that YNAB has introduced some new enumerations and they need to be added now.

Error: Error converting value "mortgage" to type 'YNAB.Rest.AccountType'. Path 'data.accounts[31].type', line 1, position 10715.

Where did you get the different YNAB accounts types from?

`    public enum AccountType
    {
        Checking,
        Savings,
        Cash,
        CreditCard,
        LineOfCredit,
        OtherAsset,
        OtherLiability,
        Mortgage
    }`

**Comment by websmartcentral** [comment]
i've fix this in my branch - just needs to be merged back - would someone approve my pull request

**Comment by jsmarble** [comment]
Merged
